# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AMoAdMoPubDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'mopub-ios-sdk'
  # Pods for AMoAdMoPubDemo

  target 'AMoAdMoPubDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AMoAdMoPubDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
